DGRPTX8 ; ;08/22/16
 S X=DE(29),DIC=DIE
 ;
 S X=DE(29),DIC=DIE
 ;
 S X=DE(29),DIC=DIE
 ;
 S X=DE(29),DIC=DIE
 D AUTOUPD^DGENA2(DA)
 S X=DE(29),DIC=DIE
 X "S DFN=DA D EN^DGMTR K DGREQF"
 S X=DE(29),DIC=DIE
 D EVENT^IVMPLOG(DA)
