CLEARMEA(MSET,MEAS)     ; DELETE AND THEN RECREATE AS EMPTY THE
        ; MEASURE MEAS IN MEASURE SET IEN MSET
        ;
        N C0QFDA,MFN,MEASURE
        S MFN=$$C0QMMFN() ; FILE NUMBER FOR MEASURE SUBFILE
        D CLEAN^DILF
        S MEASURE=$$GET1^DIQ(MFN,MEAS_","_MSET_",",.01,"I") ;  MEASURE POINTER
        D CLEAN^DILF
        K ZERR
        S C0QFDA(MFN,MEAS_","_MSET_",",.01)="@" ; GET READY TO DELETE THE MEASURE
        D FILE^DIE(,"C0QFDA","ZERR") ; KILL THE SUBFILE
        I $D(ZERR) S ZZERR=ZZERR ; ZZERR DOESN'T EXIST, INVOKE THE ERROR TRAP IF TASKED
        ;. W "ERROR",!
        ;. ZWR ZERR
        ;. B
        K C0QFDA
        S C0QFDA(MFN,"+1,"_MSET_",",.01)=MEASURE ; GET READY TO RECREATE THE SUBFILE
        D UPDIE ; CREATE THE SUBFILE
        Q

