test17  ;
 N DGNEWDT,DGFILE,DGDA,DGIENS,FDA
 S DGFILE=$P(DAS,";",2)
 I DGFILE'="P"&(DGFILE'="S") Q
 I DGFILE="P" S DGFILE=45.05
 I DGFILE="S" S DGFILE=45.01
 I DGFILE="A",DGFILE="B" S DGFILE=45.03
 I DGFILE="C",DGFILE2="D" S DGFILE=45.04
 S FDA(DGFILE,DGIENS,.01)=DGNEWDT
 D FILE^DIE("K","FDA")
 Q
